[package]
name = "loomz-engine"
version = "0.1.0"
edition = "2021"

[features]


[dependencies]
raw-window-handle = { version = "0.6" }
fnv = "1.0.3"
bitflags = "2.6.0"

loomz-shared = { path = "../loomz-shared" }
loomz-engine-core = { path = "../loomz-engine-core" }
vk = { path = "../vk" }
