[package]
name = "loomz-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[features]
default = []
hot-reload = []

[dependencies]
loomz-shared = { path = "../loomz-shared" }
serde_json = "1.0"
