[package]
name = "loomz-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[features]
default = []
hot-reload = []

[dependencies]
loomz-shared = { path = "../loomz-shared" }
jsonic = "0.2.12"
