[workspace]
resolver = "2"
members = [
    "vk",
    "tools",
    "loomz-shared",
    "loomz-engine-core",
    "loomz-engine",
    "loomz-client",
    "loomz", 
]

[profile.release]
opt-level = 2
strip = "debuginfo"
panic = "abort"
