[workspace]
resolver = "2"
members = [
    "vk",
    "loomz-tools",
    "loomz-shared",
    "loomz-engine-core",
    "loomz-engine",
    "loomz-client",
    "loomz", 
]

[profile.dev]
debug = 0
strip = "debuginfo"

[profile.release]
opt-level = 2
strip = "debuginfo"
#panic = "abort"
