[package]
name = "loomz-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
fnv = "1.0.3"
parking_lot = "0.12.3"
bitflags = "2.6.0"
png = "0.17.14"
unicode-segmentation = "1.12"

vk = { path = "../vk" }
